### ISSUE TITLE
Image Matching Trigger

### ISSUE THREAD

**Issue by luxuc** [baggage-recovery-app/Baggage-Recovery-App#2]
The matching function should start running:
1. everyday
2. every time when a new bag is registered into DB

**Comment by neemay** [comment]
RESOLVED: there will be 2 batches of image matching.
1) When a bag is done being registered, it will automatically trigger a matching between this bag and potential reports.
2) If this bag doesn't match any reports, it is put aside. If the bag is a match, this report is closed.
3) Once all of the day's bags are registered, someone will run the image matching again but from the reports side. Then they can see the potential bags for this report.
